//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStok.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCSTOK2Entities : DbContext
    {
        public MVCSTOK2Entities()
            : base("name=MVCSTOK2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLKAtegoriler> TBLKAtegoriler { get; set; }
        public virtual DbSet<TBLMusteriler> TBLMusteriler { get; set; }
        public virtual DbSet<TBLSatıslar> TBLSatıslar { get; set; }
        public virtual DbSet<TBLUrunler> TBLUrunler { get; set; }
    }
}
